export default {
  login: "bpinazmul18",
  id: 48866588,
  node_id: "MDQ6VXNlcjQ4ODY2NTg4",
  avatar_url: "https://avatars.githubusercontent.com/u/48866588?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/bpinazmul18",
  html_url: "https://github.com/bpinazmul18",
  followers_url: "https://api.github.com/users/bpinazmul18/followers",
  following_url:
    "https://api.github.com/users/bpinazmul18/following{/other_user}",
  gists_url: "https://api.github.com/users/bpinazmul18/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/bpinazmul18/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/bpinazmul18/subscriptions",
  organizations_url: "https://api.github.com/users/bpinazmul18/orgs",
  repos_url: "https://api.github.com/users/bpinazmul18/repos",
  events_url: "https://api.github.com/users/bpinazmul18/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/bpinazmul18/received_events",
  type: "User",
  site_admin: false,
  name: "Md Nazmul Haque",
  company: null,
  blog: "",
  location: "Sirajganj",
  email: null,
  hireable: null,
  bio: "\r\nI never stop learning :)",
  twitter_username: "devnazmul20",
  public_repos: 85,
  public_gists: 0,
  followers: 6,
  following: 217,
  created_at: "2019-03-23T19:03:15Z",
  updated_at: "2021-06-03T05:28:47Z",
};
